### ISSUE TITLE
Swift: Issue with pagination and receivedQueryResult: not firing

### ISSUE THREAD

**Issue by tahoecoop** [Factual/factual-ios-sdk#7]
EDIT: Updated code for query as I have it now.

Hello! Below is my code to get results from the Factual API. When loading the data initially (before tableview is moving), `receivedRawResult:` fires quickly after I call `_apiObject.get("t/places-us", params: params as [NSObject : AnyObject], withDelegate:  #self)`. When user is scrolling through results on the tableview, I call queryTable again with the offset to get the next set of results. However, `receivedQueryResult:` doesn't go in there while user is scrolling. It only gets the results when the tableview stops moving. It seems to me this is a threading issue as I can stop scrolling and it will load, or it loads when getting to the end of the tableview. I tried to wrap everything in GCD calls to get it on the main thread, but no dice. Any ideas? Thanks again!

WHERE I AM CALLING FOR MORE PLACES:

```
   func tableView(tableView: UITableView, willDisplayCell cell: UITableViewCell, forRowAtIndexPath indexPath: NSIndexPath) {

      // it will only try to load more places if the first run of results returned a full 25 places
      if skipCount >= 25 {

         if indexPath.row == skipCount - 9 && skipCount < 79 {

            self.setUpCallToFactualFromUserLocation(self.userNewLocation, skipCount: self.skipCount, isPaginationLoad: true, isComingFromSearch: false)
         }
      }
   }
```

CALL TO FACTUAL:
```
func setUpCallToFactualFromUserLocation(userLocation:CLLocation, skipCount:Int, isPaginationLoad:Bool, isComingFromSearch:Bool) {

      // adding filter for category id 347 (restaurants), 312 (bars), 338 (food & dining), 370 (wineries and vineyards)
      let filters = NSMutableDictionary()
      let includesAny = NSMutableDictionary()
      let categories: NSMutableArray = [347, 312, 338,370]

      includesAny.setValue(categories, forKey: "$includes_any")
      filters.setValue(includesAny, forKey: "category_ids")

      let coords = NSMutableArray()
      coords.addObject(userLocation.coordinate.latitude)
      coords.addObject(userLocation.coordinate.longitude)

      let centerFilter = NSMutableDictionary()
      centerFilter.setValue(coords, forKey: "$center")
      centerFilter.setValue(5000, forKey: "$meters")

      let geoFilter = NSMutableDictionary()
      geoFilter.setValue(centerFilter, forKey: "$circle")

      let params = NSMutableDictionary()
      params.setValue("confident", forKey: "threshold")
      params.setValue("25", forKey: "limit")
      params.setValue(filters, forKey: "filters")
      params.setValue(geoFilter, forKey: "geo")
      params.setValue("$distance:asc", forKey: "sort")
      params.setValue(String(skipCount), forKey: "offset")

      _apiObject.get("t/places-us", params: params as [NSObject : AnyObject], withDelegate: self)
   }

```

**Comment by tahoecoop** [comment]
Any word? Is this something you guys have noticed or is it something I'm doing wrong on my end? Thank you!!

**Comment by gateway** [comment]
@BradleyFactual Any thoughts on this.. would be greatly appreciated..

**Comment by tahoecoop** [comment]
Any word on this @BradleyFactual ? We are releasing a version of the app in couple days and we'd love to have clean pagination. Any feedback you can provide on this issue? Thanks a ton!!

**Comment by BradleyFactual** [comment]
I don't. Unfortunately, I'm not versed in objective-C. Was hoping someone in the support forums might have hit a problem similar to this before.

**Comment by BradleyFactual** [comment]
Can you guys get unstuck here by just requesting more pages prior to scrolling?

**Comment by tahoecoop** [comment]
Thanks for the response Bradley!  So in my code, I am requesting the next set of data before user gets to the bottom of the tableview. The query request is going through fine at this time, no issues. However, where I would get the results back in `receivedRawData:`, this method doesn't get called until the user stops scrolling the tableview. I have scrolled it up and down for over 30 seconds and it doesn't fire until I stop scrolling. So to me, it looks like the tableview is blocking `receivedRawResults:` somehow. On my end, I've tried wrapping everything in GCD queues, no dice. Is there an iOS engineer over there that can take a look at this issue? The pagination works, as far as getting more places, it just looks really bad as the results don't pop up until user smacks into the bottom of the tableview. Thanks again!!!

**Comment by BradleyFactual** [comment]
There's a max page limit, and a max offset limit. If I set your page limit and your offset limit to be the same, you can just pull the full page at once, and therefore not have to refresh the page. Would that get you unstuck for now?

**Comment by tahoecoop** [comment]
I can fudge it for now and make it look ok. But can you still have an engineer look at this issue so we can have proper paging soon? Thanks again for all the help Bradley, really appreciate it!

**Comment by tahoecoop** [comment]
Hi @BradleyFactual, just wanted to follow up and see what we can do about this issue with pagination. I still am having the same issue and really would love to get to the bottom of this so I can use real pagination. Thanks again for your assistance!!

**Comment by gateway** [comment]
@BradleyFactual any ideas on this, its holding is up and wanted to get your opinion on what might how we can get this rolling.. Thanks

**Comment by tahoecoop** [comment]
@BradleyFactual Any help on this issue would be awesome, thanks again!!

**Comment by gateway** [comment]
@BradleyFactual hey man, any chance you could help out, been waiting on this but we are trying to get set up for the app store soon and this is the last factual issue we are needing to resolve.

**Comment by BradleyFactual** [comment]
I'd say the best solution here right now is for us to give you maximum pagination on the first request, meaning, you don't need to fire a second request to get the rest of the data. That would obviate the condition completely, no?

**Comment by BradleyFactual** [comment]
How deep are you paging currently? Meaning, the deepest offset your users practically hit?

**Comment by gateway** [comment]
@BradleyFactual  That might be a solution, right now we can only pull in I think max 50 results based upon the geo location.  If your saying that our account would be set to return all results in x,y,z categories that you would then send us lets say instead of 50, the max of what was in that area, so if it was 150 places that would be returned to us, thus eliminating the pagination?

**Comment by BradleyFactual** [comment]
I'm not sure I can set to "all" results, because that's indeterminate, but I can give you a sufficiently large limit to solve this. What would be a practical limit that your users would not page beyond, for example?

**Comment by gateway** [comment]
well, I think a value of like 200 (about 4 pages) would do it, most areas will not even return that amount but that should be safe.
