### ISSUE TITLE
How to get multiple places back when querying with array of factual_ids?

### ISSUE THREAD

**Issue by tahoecoop** [Factual/factual-ios-sdk#8]
Hello, I have the need to be able to request place data for multiple places at once from an array of factual_ids. However, I get an error: `generateErrorCallback:2 error:The $includes_any operator cannot be applied on field 'factual_id'.  For documentation, please see: http://developer.factual.com.` Is there a way to put this request together? I tried to do it 2 ways, both give me the error. How can I accomplish this? Thanks!

1st way:
   ```
func setUpCallToFactualForArrayOfLocationIDs(placeFactualIds:[String]) {
      let queryObject:FactualQuery = FactualQuery.makeQuery()
      queryObject.addRowFilter(FactualRowFilter.fieldName("factual_id", includesAnyArray: placeFactualIds))
      _apiObject.queryTable("restaurants-us", optionalQueryParams: queryObject, withDelegate: self)
   }
```
2nd way:
  ```
 func lookUpPlacesByLocationIDs(locationIDs:[String]) {
      let filters = NSMutableDictionary()
      let includesAny = NSMutableDictionary()
      includesAny.setValue(locationIDs, forKey: "$includes_any")
      filters.setValue(includesAny, forKey: "factual_id")
      let params = NSMutableDictionary()
      params.setValue(filters, forKey: "filters")
      _apiObject.get("t/places-us", params: params as [NSObject:AnyObject], withDelegate: self)
   }
```

**Comment by BradleyFactual** [comment]
**$includes_any** is only for filtering against multi-valued columns (for example, *category_ids*). You want to use **$in** for this.

**Comment by tahoecoop** [comment]
Hey Bradley, thanks for the quick reply! So I tried using `$in` instead of `$includes_any`, I'm not getting any errors but also not getting results. I ensured that the `locationIDs` array has a factual_id at each index. Here is the query, any idea what I'm missing? I really appreciate it!

 ```
  func lookUpPlacesByLocationIDs(locationIDs:[String]) {

      // casting swift array to nsarray, I also tried with the swift array and it didn't work either
      let nsArrayOfIds = NSArray(array: locationIDs)
      let filters = NSMutableDictionary()
      let includesAny = NSMutableDictionary()

      includesAny.setValue(nsArrayOfIds, forKey: "$in")
      filters.setValue(includesAny, forKey: "factual_id")

      let params = NSMutableDictionary()
      params.setValue(filters, forKey: "filters")

      _apiObject.get("t/places-us", params: params as [NSObject:AnyObject], withDelegate: self)
   }
```

**Comment by gateway** [comment]
@BradleyFactual I can also confirm this doesnt *seem* to work.

We are both trying to hit this, I tested it in the php sdk with the following code

`  $query = new FactualQuery;
  $query->field("factual_id")->in(array("ChIJ50EYjse1j4ARQAvOtT-s7_g", "ChIJFR6rI4-AhYAR7C9RLHJ4TwI"));
  $res = $factual->fetch("places", $query);
  $factual->debug();
  
  d($res->getData());
  d($factual);
`

debug doesnt tell me anything.. just list the following.

`Factual Object
(
    [factHome:protected] => http://api.v3.factual.com/
    [signer:protected] => OAuthStore2Leg Object
        (
            [consumer_key:protected] => xxx
            [consumer_secret:protected] => xxx
            [signature_method:protected] => Array
                (
                    [0] => HMAC-SHA1
                )

            [token_type:protected] => 
        )

    [config:protected] => Array
        (
            [factual] => Array
                (
                    [endpoint] => http://api.v3.factual.com/
                    [driverversion] => factual-php-driver-v1.5.8
                )

        )

    [geocoder:protected] => 
    [configPath:protected] => config.ini
    [lastTable:protected] => places
    [fetchQueue:protected] => Array
        (
        )

    [debug:protected] => 1
    [curlTimeout:protected] => 0
    [connectTimeout:protected] => 0
)`

any ideas?

**Comment by BradleyFactual** [comment]
Where did you get ChIJ50EYjse1j4ARQAvOtT-s7_g? That's not a Factual Id.

**Comment by BradleyFactual** [comment]
Also, this seems more like a help request than a bug in the driver. I'd like to suggest that this discussion really belongs in the support forum, in case others can profit from the knowledge: support.factual.com.

**Comment by gateway** [comment]
@BradleyFactual no where in the code can I see anything that accepts factual_id.. so I think the most important part would be does the value of in work with id's.. the prob with the forum is lack of returned responses we waited a few months before so we are very grateful for your help because , the hold up for us to even use Factual was the lack of support we where getting..

**Comment by BradleyFactual** [comment]
I'm referring to this line of code, re: factual_id:

```
  $query->field("factual_id")->in(array("ChIJ50EYjse1j4ARQAvOtT-s7_g", "ChIJFR6rI4-AhYAR7C9RLHJ4TwI"));
```
Those aren't factual ids. Factual Ids are always GUIDs, so that's why you are receiving no results.
